######################################################################
# Automatically generated by qmake (2.01a) Sun Mar 23 14:32:48 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += FittsWidget.h main_window.h
SOURCES += main_window.cpp
